In [1]:
print("Hello")

Hello


In [2]:
## importing the numpy libraries

import numpy as np

In [4]:
my_list = [1,2,3,4,5]

arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(arr)

[1 2 3 4 5]


In [8]:
arr.shape

(5,)

In [9]:
## multinested array

my_list1 = [1,2,3,4,5]
my_list2 = [2,3,4,5,6]
my_list3 = [9,7,6,8,9]

arr=np.array([my_list1,my_list2,my_list3])

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
arr.shape

(3, 5)

In [16]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [18]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [22]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

Indexing

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [26]:
arr[3:4,3:4]

array([], shape=(0, 1), dtype=int64)

In [28]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [34]:
 arr[1:3,2:4]

array([[4, 5],
       [6, 8]])

In [40]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [41]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [42]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [43]:
array=np.arange(0,10,

SyntaxError: unexpected EOF while parsing (<ipython-input-43-9331dee4efc0>, line 1)

In [44]:
array=np.arange(0,10)

In [45]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
array=np.arange(0,10,step =2)

In [47]:
array

array([0, 2, 4, 6, 8])

In [48]:
 np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [52]:
## copy function and the broadcast function

array[3:] = 100

In [51]:
array

array([  0,   2,   4, 100, 100])

In [54]:
arr1= array

In [55]:
arr1[3:] = 500
print(arr1)

[  0   2   4 500 500]


In [56]:
array


array([  0,   2,   4, 500, 500])

In [57]:
arr1 = array.copy()

In [65]:
print(array)
arr1[3:] =1000
print(arr1)

2
[   0    2    4 1000 1000]


In [70]:
### some conditions very useful in Exploratory Data Anlaysis 

val = 2

arr[arr<300]

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9])

In [72]:
## create arryas and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [77]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [81]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
## Random Distribution
np.random.rand(3,3 )

array([[0.67511956, 0.53130419, 0.48867558],
       [0.69053083, 0.10149336, 0.89916621],
       [0.70603941, 0.88040325, 0.84701817]])

In [89]:
arr_ex = np.random.randn(4,4)

In [90]:
arr_ex

array([[-1.53230507,  0.545412  , -0.14330699,  0.08496673],
       [-0.47238845, -1.17986549,  0.79700387, -1.68640343],
       [-0.53328277,  1.46612373, -0.09812007,  0.45745318],
       [-1.7080479 , -0.7335705 ,  0.13615716, -0.12774635]])

In [93]:
import seaborn as sns 

ModuleNotFoundError: No module named 'seaborn'